config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "receipts#index"
  resources :users do
    resources :receipts do
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/login',   to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  validates :usage_date, presence: true
  validates :price, presence: true
  validates :usage, presence: true
  validates :publisher, presence: true
  mount_uploader :img, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :receipts, dependent: :destroy
  has_secure_password validations: true
  validates :login_id, presence: true
  validates :sei, presence: true
  validates :mei, presence: true
  validates :sei_kana, presence: true
  validates :mei_kana, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :logged_in_user

  def index
    @receipts = current_user.receipts.all.order(usage_date: "DESC") 
    @user = current_user
    @receipt_total = Receipt.all.sum(:price)
  end

  def show
    @receipt = current_user.receipts.find(params[:id])
  end

  def new
    @receipt = current_user.receipts.build
    @user = current_user
  end

  def create
    @receipt = Receipt.new(receipt_params)
    if @receipt.save!
      flash[:danger] = "セーブに成功しました"
      redirect_to user_receipts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @receipt = current_user.receipts.find(params[:id])
  end

  def update
    begin
      @receipt = current_user.receipts.find(params[:id])
      @receipt.update(receipt_params)
      redirect_to user_receipts_path(current_user)
    rescue ActiveRecord::RecordNotFound => e
      falsh[:danger] = "指定したIDのレシートが見つかりませんでした"
    rescue 
      render :edit
    end
  end

  def update
    begin
      @receipt = current_user.receipts.find(params[:id])
      @receipt.update(receipt_params)
      redirect_to user_receipts_path(current_user)
    rescue ActiveRecord::RecordNotFound => e
      falsh[:danger] = "指定したIDのレシートが見つかりませんでした"
    rescue 
      render :edit
    end
  end

  private
    def receipt_params
      params.require(:receipt)
      .permit(:usage_date,:price,:usage,:publisher,:img).merge(user_id: params[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(login_id: params[:session][:login_id])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(User_params)
    if @user.save
      redirect_to user_path
    else
      render :new
    end
  end

  private
    def User_params
      params.require(:user)
      .permit(:login_id, :password, :sei, :mei, :sei_kana, :mei_kana)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>家計簿アプリ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/receipts/_form.html.erb
<div class="card-body">
  <div class="form-group">
    <%= form.file_field :img, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :usage_date, "利用年月日", class: "form-label" %>
    <%= form.date_field :usage_date, value: Date.today, class: "form-control" %>
    <% if @receipt.errors.include?(:usage_date) %>
      <span class="help-block"><%= @receipt.errors.full_messages_for(:usage_date).first %></span>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :price, "金額", class: "form-label" %>
    <%= form.number_field :price, class: "form-control" %>
    <% if @receipt.errors.include?(:usage_date) %>
      <span class="help-block"><%= @receipt.errors.full_messages_for(:price).first %></span>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :usage, "用途", class: "form-label" %>
    <%= form.text_field :usage, class:"form-control" %>
    <% if @receipt.errors.include?(:usage) %>
      <span class="help-block"><%= @receipt.errors.full_messages_for(:usage).first %></span>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :publisher, "発行元", class: "form-label" %>
    <%= form.text_field :publisher, class:"form-control" %>
    <% if @receipt.errors.include?(:publisher) %>
      <span class="help-block"><%= @receipt.errors.full_messages_for(:publisher).first %></span>
    <% end %>
  </div>
  <%= hidden_field_tag :user_id, @receipt.user_id %>
  <div class="card-footer">
    <%= form.submit value="登録", class:"btn btn-secondary" %>
  </div>
</div>

app/views/receipts/edit.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/sidebar' %>
<!-- body -->
<div class="content-wrapper h-100">
    <section class="content">
      <div class="row">
        <!-- box col-12 -->
        <div class="col-sm-6 offset-md-4 mt-5">
          <div class="card card-secondary">
            <div class="card-header">
                レシート編集
            </div>
            <%= form_with(model: @receipt, url: user_receipt_path(@receipt.user_id,@receipt), method: :patch) do |form| %>
              <%= render partial: "form", locals: {form: form, receipt: @receipt} %>
            <% end %>
          </div>
        </div>
      </div>
    </section>
</div>

app/views/receipts/index.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/sidebar' %>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper h-100">
  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="col-12 clearfix py-4">
        <div class="float-left test-box">
          <span>支出</span>
          <h1>￥<%= @receipt_total %></h1>
        </div>
        <div class="float-right test-box">
          <%= link_to "レシート登録", new_user_receipt_path(@user), {class: "btn btn-info"} %>
        </div>
      </div>
      <% if !@receipts.empty? %>
        <div class="card">
          <div class="card-body p-0">
            <table class="table table-sm">
              <thead>
                <tr>
                  <th>金額</th>
                  <th>利用店</th>
                  <th>日付</th>
                </tr>
              </thead>
              <tbody>
                <% @receipts.each do |receipt| %>
                  <tr>
                    <td><%= link_to user_receipt_path(@user,receipt) do %>￥<%= receipt.price %><% end %></td>
                    <td><%= link_to receipt.publisher, user_receipt_path(@user,receipt) %></td>
                    <td><%= link_to receipt.usage_date, user_receipt_path(@user,receipt) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->
</div>

app/views/receipts/new.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/sidebar' %>
<!-- body -->
<div class="content-wrapper h-100">
    <section class="content">
      <div class="row">
        <!-- box col-12 -->
        <div class="col-sm-6 offset-md-4 mt-5">
          <div class="card card-secondary">
            <div class="card-header">
                レシート新規登録
            </div>
            <%= form_with(model: @receipt, url: user_receipts_path) do |form| %>
              <%= render partial: "form", locals: {form: form, receipt: @receipt} %>
            <% end %>
          </div>
        </div>
      </div>
    </section>
</div>

app/views/receipts/show.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/sidebar' %>
<div class ="content-wrapper h-100">
  <section class="content pt-5">
    <div class="card card-solid">
      <div class="card-body">
        <div class="row">
          <div class="col-12 col-sm-6 text-center d-flex align-items-center">
            <div class="col-12">
              <% if @receipt.img.url %>
                <%= image_tag @receipt.img.url %>
              <% else %>
                <%= image_tag 'no_image.jpg' %>
              <% end %>
            </div>
          </div>
          <div class="col-12 col-sm-6">
            <h1 class="my-3"><span>金額</span>￥<%= @receipt.price %></h1>
            <hr>
            <h3 class="my-3"><span>利用店</span><%= @receipt.publisher %></h3>
            <hr>
            <h3 class="my-3"><span>用途</span><%= @receipt.usage %></h3>
            <hr>
            <h3 class="my-3"><span>利用日</span><%= @receipt.usage_date %></h3>
            <hr>
            <h3 class="my-3"><span>登録日</span><%= @receipt.created_at %></h3>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to '削除', user_receipt_path(current_user,@receipt), class:"btn btn-danger px-5 mx-2 float-right", method: :delete %>
          <%= link_to '編集', edit_user_receipt_path(current_user,@receipt), class:"btn btn-warning px-5 mx-2 float-right", method: :delete %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/shared/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="/" class="brand-link">
    <%= image_tag 'kakeibo.png', class:"brand-image", style:"opacity: .8" %>
    <%# <img src="/assets/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> %>
    <span class="brand-text font-weight-light">家計簿アプリ</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to user_receipts_path(current_user), class: "nav-link" do %>
            <i class="nav-icon fas fa-th"></i>
            <p>
              レシート管理
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <% if logged_in? %>
            <%= link_to logout_path, class: "nav-link", data: { turbo_method: :delete } do %>
              <i class="nav-icon fas fa-th"></i>
              <p>
                ログアウト
              </p>
            <% end %>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/users/index.html.erb
ユーザー一覧